Film_and_Review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('comments/', include('django_comments.urls')),
    ]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    ]

catalog/urls.py
from django.urls import path
from .views import MovieCreateView, MovieDescrCreateView, ActorAddView, CrewAddView
from .views import MovieList, statistics, InfoView
urlpatterns = [path('', MovieList.as_view(), name='index'),
               path('add/', MovieCreateView.as_view(), name='add'),
               path('add_description/', MovieDescrCreateView.as_view(), name='add_description'),
               path('add_actor/', ActorAddView.as_view(), name='add_actor'),
               path('add_crew/', CrewAddView.as_view(), name='add_crew'),
               path('statistics/', statistics, name='statistics'),
               path('movie/<int:pk>', InfoView.as_view(), name='movie_info'),
]

catalog/models.py
from django.db import models
from django.urls import reverse


class Movie(models.Model):
    title = models.CharField(max_length=50, verbose_name='Title')
    directed_by = models.CharField(max_length=50, null=True, blank=True, verbose_name='Directed by')
    genre = models.CharField(max_length=90, null=True, blank=True, verbose_name='Genre')
    year = models.IntegerField(verbose_name='Year')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'films'
        verbose_name = 'film'


class MovieDescription(models.Model):
    movie = models.OneToOneField('Movie', on_delete=models.CASCADE, null=True)
    synopsis = models.TextField(null=True, blank=True, verbose_name='Synopsis')
    rate = models.FloatField(null=True, blank=True, verbose_name='Rate')

    def __str__(self):
        if len(self.synopsis) >= 30:
            return f' {self.synopsis[0:30]}...'
        return self.synopsis

    class Meta:
        verbose_name_plural = 'descriptions'
        verbose_name = 'description'

    def get_absolute_url(self):
        return reverse('movie_info', args=[str(self.pk)])


class Cast(models.Model):
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE, null=True)
    role = models.CharField(max_length=90, null=True, blank=True, verbose_name='Role')
    name = models.CharField(max_length=90, null=True, blank=True, verbose_name='Name')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'actors'
        verbose_name = 'actor'


class Staff(models.Model):
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=90, null=True, blank=True, verbose_name='Name')
    position = models.CharField(max_length=90, null=True, blank=True, verbose_name='Position')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'film crew members'
        verbose_name = 'film crew member'

catalog/forms.py
from django.forms import ModelForm
from .models import Movie, MovieDescription, Cast, Staff


class MovieAddingForm(ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'directed_by', 'year', 'genre', )


class MovieDescriptionAddingForm(ModelForm):
    class Meta:
        model = MovieDescription
        fields = ('movie', 'synopsis', 'rate', )


class ActorAddingForm(ModelForm):
    class Meta:
        model = Cast
        fields = ('movie', 'role', 'name',)


class CrewAddingForm(ModelForm):
    class Meta:
        model = Staff
        fields = ('movie', 'position', 'name',)

catalog/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Movie, MovieDescription, Cast
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import DetailView, ListView
from .forms import MovieAddingForm, MovieDescriptionAddingForm, ActorAddingForm, CrewAddingForm
from django.db.models import Avg, Q
from django_comments.models import Comment
from django.contrib.auth.mixins import LoginRequiredMixin


class MovieList(ListView):
    template_name = 'catalog/index.html'
    model = MovieDescription
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        descr = MovieDescription.objects.all()
        context['descriptions'] = {'descriptions': descr}
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return MovieDescription.objects.filter(Q(movie__title__icontains=query) |
                                                   Q(movie__year__icontains=query) |
                                                   Q(movie__genre__icontains=query) |
                                                   Q(movie__directed_by__icontains=query) |
                                                   Q(synopsis__icontains=query) |
                                                   Q(movie__cast__role__icontains=query) |
                                                   Q(movie__cast__name__icontains=query) |
                                                   Q(movie__staff__name__icontains=query) |
                                                   Q(movie__staff__position__icontains=query)
                                                   ).distinct()
        else:
            return MovieDescription.objects.all()


def statistics(request):
    template = loader.get_template('catalog/statistics.html')
    num_films = Movie.objects.all().count()
    num_actors = Cast.objects.all().count()
    comment_count = Comment.objects.all().count()
    av_rate = MovieDescription.objects.all().aggregate(Avg('rate'))
    context = {
        'num_films': num_films,
        'num_actors': num_actors,
        'av_rate': round(av_rate['rate__avg'], 2),
        'comment_count': comment_count,
            }
    return HttpResponse(template.render(context, request))


class MovieCreateView(LoginRequiredMixin, CreateView):
    template_name = 'catalog/create.html'
    form_class = MovieAddingForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class MovieDescrCreateView(LoginRequiredMixin, CreateView):
    template_name = 'catalog/add_description.html'
    form_class = MovieDescriptionAddingForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ActorAddView(LoginRequiredMixin, CreateView):
    template_name = 'catalog/add_actor.html'
    form_class = ActorAddingForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CrewAddView(LoginRequiredMixin, CreateView):
    template_name = 'catalog/add_crew.html'
    form_class = CrewAddingForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class InfoView(DetailView):
    template_name = 'catalog/movie_info.html'
    model = MovieDescription
    context_object_name = 'MovieDescription'

catalog/templates/catalog/add_actor.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta  http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Adding an actor - Film and Review</title>
    </head>
    <body>
        <h1>Adding an actor</h1>
            <div>
                <a href="{% url 'index' %}">Back to the main page</a>
            </div>
        <form method="post"> {% csrf_token %} {{ form.as_p }}
            <input type="submit" vаluе="Add">
        </form>
    </body>
</html>

catalog/templates/catalog/add_crew.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta  http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Adding a crew member - Film and Review</title>
    </head>
    <body>
        <h1>Adding a crew member</h1>
            <div>
                <a href="{% url 'index' %}">Back to the main page</a>
            </div>
        <form method="post"> {% csrf_token %} {{ form.as_p }}
            <input type="submit" vаluе="Add">
        </form>
    </body>
</html>

catalog/templates/catalog/add_description.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta  http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Adding a description - Film and Review</title>
    </head>
    <body>
        <h1>Adding a description</h1>
            <div>
                <a href="{% url 'index' %}">Back to the main page</a>
            </div>
        <form method="post"> {% csrf_token %} {{ form.as_p }}
            <input type="submit" vаluе="Add">
        </form>
    </body>
</html>

catalog/templates/catalog/comment.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta  http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Adding a comment - Film and Review</title>
    </head>
    <body>
        <h1>Adding a comment</h1>
            <div>
                <a href="{% url 'index' %}">Back to the main page</a>
            </div>
        <form method="post"> {% csrf_token %} {{ form.as_p }}
            <input type="submit" vаluе="Comment">
        </form>
    </body>
</html>

catalog/templates/catalog/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta  http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Adding a movie - Film and Review</title>
    </head>
    <body>
        <h1>Adding a movie</h1>
            <div>
                <a href="{% url 'index' %}">Back to the main page</a>
            </div>
        <form method="post"> {% csrf_token %} {{ form.as_p }}
            <input type="submit" vаluе="Add">
        </form>
    </body>
</html>

catalog/templates/catalog/index.html
{% extends "base_generic.html" %}
{% block content %}
<div>
<h1>Films and Review</h1>
    <form method="GET" action="">
          <input name="q" type="text" value="{{ request.GET.q }}" placeholder="Search by title, year, genre, synopsis"/>
    </form>
</div>
{% for d in object_list %}
<div>
    <h2><a href="{{ d.get_absolute_url }}">{{ d.movie }} ({{ d.movie.year }})</a></h2>
    <p> Directed by {{ d.movie.directed_by }}</p>
    <p> {{ d.movie.genre}}</p>
</div>
{% endfor %}
<div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span>
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
</div>
{% endblock %}

catalog/templates/catalog/movie_info.html
{% extends "base_generic.html" %}
{% block content %}
{% load comments %}
<h1>Info</h1>
<h3>{{ MovieDescription.movie}} ({{MovieDescription.movie.year}})</h3>
<p>{{ MovieDescription.synopsis}}</p>
<p>IMDB: {{ MovieDescription.rate}}</p>
<table><tr><td><h3>Cast</h3></td><td><h3>Crew</h3></td></tr>
<td>
<ul>
    {% for actor in MovieDescription.movie.cast_set.all %}
        <li>{{actor}} as {{actor.role}}</li>
    {% endfor %}
</ul>

</td>
 <td>
 <ul>
     <li>{{MovieDescription.movie.directed_by}} as director</li>
    {% for member in MovieDescription.movie.staff_set.all %}
        <li> {{member}} as {{member.position}}</li>
    {% endfor %}
</ul>

 </td>
    <tr><td>
        <h4>Add a comment</h4>
        {% if user.is_authenticated %}
            {% render_comment_form for MovieDescription.movie %}
        {% else %}
            <p>Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
        {% endif %}
    </td>
    {% get_comment_count for MovieDescription.movie as comment_count %}
    <td valign="top"><h4>Comments {{comment_count}}</h4>
    {% render_comment_list for MovieDescription.movie %}</td>
    </tr>
</table>


{% endblock %}

catalog/templates/catalog/statistics.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Statistics</h1>
<ul type="square">
    <li>{{ num_films }} movies;</li>
    <li>{{ num_actors }} actors;</li>
    <li>{{ comment_count }} comments;</li>
    <li>{{ av_rate }} average rate.</li>
</ul>
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Films and Review</title>
</head>
<body>
<table cellspacing=25>
<td valign="top">
{% block sidebar %}
<ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %}
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'add' %}">Add a movie</a></li>
    <li><a href="{% url 'add_description' %}">Add a description</a></li>
    <li><a href="{% url 'add_actor' %}">Add an actor</a></li>
    <li><a href="{% url 'add_crew' %}">Add a crew member</a></li>
    <li><a href="{% url 'statistics' %}">Statistics</a></li>
  </ul>
{% endblock %}
    </td>
    <td valign="top">
{% block content %}
{% endblock %}
    </td>
</table>
</body>
</html>